"""delete unique password

Revision ID: 12eec6e2b48d
Revises: e83092cef810
Create Date: 2020-04-16 18:57:38.910259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12eec6e2b48d'
down_revision = 'e83092cef810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('password', table_name='person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('password', 'person', ['password'], unique=True)
    # ### end Alembic commands ###
