"""unique password

Revision ID: e83092cef810
Revises: 1cde423aff83
Create Date: 2020-04-16 18:56:51.431706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e83092cef810'
down_revision = '1cde423aff83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'person', ['password'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='unique')
    # ### end Alembic commands ###
